### ISSUE TITLE
The default stride can be smaller for better efficiency!

### ISSUE THREAD

**Issue by RuoyiDu** [lucataco/cog-demoFusion#1]
Hi Luis,

Thanks for your implementation of our DemoFusion. But I suggest that you can set a larger stride size to achieve better efficiency. E.g., a stride of 64 leads to generating 3072 images within 6 mins. Please check the example: https://replicate.com/p/oldtopdbasnqk5lfbtggdtkxeq?input=form.

This might make more people willing to try it - not everyone can wait 20min.

**Comment by lucataco** [comment]
Oh wow, thank you for the fix, and for sharing your Replicate run! 
Let us know if you'd like to move the official model under your Replicate account. 
We can maintain the model for you, let us know if you're interested, thanks!

**Comment by RuoyiDu** [comment]
No need  for that! I think the most important thing is that you guys make it happen, so the demo should be under your account. We can't be recognised for our work without the support of our community! 😊

I'd also like to ask if I can include a link to this demo when I follow up to promote our work?
